# Generated by Django 2.2.12 on 2021-03-28 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=10)),
                ('kompetensi_keahlian', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Spp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField()),
                ('nominal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_bayar', models.DateField(auto_now_add=True, null=True)),
                ('waktu_dibayar', models.TimeField(auto_now_add=True, null=True)),
                ('jumlah_bayar', models.IntegerField()),
                ('id_spp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Spp')),
            ],
        ),
    ]
