# Generated by Django 2.2.12 on 2021-03-29 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pembayaran_id_siswa'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodePembayaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metode', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusPembayaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='metode_pembayaran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.MetodePembayaran'),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='status_pembayaran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.StatusPembayaran'),
        ),
    ]
