# Generated by Django 2.2.12 on 2021-03-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_metodepembayaran_keterangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodepembayaran',
            name='keterangan',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
