# Generated by Django 2.2.12 on 2021-03-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210329_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran',
            name='bukti_pembayaran',
            field=models.ImageField(null=True, upload_to='bukti-pembayaran/'),
        ),
    ]
