# Generated by Django 2.2.12 on 2021-03-31 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210329_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='status_pembayaran',
            field=models.CharField(choices=[('pending', 'Pending'), ('Pembayaran Berhasil', 'Pembayaran Berhasil')], default='pending', max_length=50),
        ),
    ]
