# Generated by Django 2.2.12 on 2021-04-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210331_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran',
            name='keterangan',
            field=models.TextField(null=True),
        ),
    ]
