# Generated by Django 2.2.12 on 2021-04-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_pembayaran_keterangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='status_pembayaran',
            field=models.CharField(choices=[('pending', 'Pending'), ('pembayaran berhasil', 'Pembayaran Berhasil')], default='pending', max_length=50),
        ),
    ]
