# Generated by Django 2.2.12 on 2021-04-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210423_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran',
            name='nama_petugas',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
