# Generated by Django 2.2.12 on 2021-03-28 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pembayaran_id_siswa'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='id_kelas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Kelas'),
        ),
        migrations.AddField(
            model_name='siswa',
            name='id_spp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Spp'),
        ),
    ]
