# Generated by Django 2.2.12 on 2021-03-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210328_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petugas',
            name='nama_petugas',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='nama',
        ),
        migrations.AddField(
            model_name='user',
            name='nama',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
