# Generated by Django 2.2.12 on 2021-04-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210329_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siswa',
            name='id_spp',
        ),
    ]
