# Generated by Django 2.2.12 on 2021-04-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='default1.jpg', null=True, upload_to='profile/'),
        ),
    ]
